name = "talms-web"
compatibility_date = "2024-04-01"

[[d1_databases]]
binding = "DB"
database_name = "talms-db"
database_id = "ebb1a487-0051-4c7a-88bc-8a72cfaaa818"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "talms-files"

[[kv_namespaces]]
binding = "KV"
id = "2c00284e99c24f15a1ee49f0dafd0c06"
